config/routes.rb
Rails.application.routes.draw do
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end
  def show
    @flat = Flat.find(params[:id])
  end
  def new
    @flat = Flat.new
  end
  def create
    @flat = Flat.new(flat_params)
    @flat.save
    redirect_to flat_path(@flat)
  end
  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy
    redirect_to flats_path
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flat_helper.rb
module FlatHelper
end

app/views/flats/index.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/flats" class="navbar-wagon-brand">
    <img src="images/logo.png" alt="logo">
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <%= link_to 'Add appartment', new_flat_path, class: 'navbar-wagon-item navbar-wagon-link'%>

    <!-- Profile picture with dropdown list -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <img src="https://kitt.lewagon.com/placeholder/users/ssaunier" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="#">Profile</a></li>
          <li><a href="#">Dashboard</a></li>
          <li><a href="#">Log Out</a></li>
        </ul>
      </div>
    </div>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Host</a></li>
        <li><a href="#">Trips</a></li>
        <li><a href="#">Messagese</a></li>
      </ul>
    </div>
  </div>
</div>


<div class="container">
  <div class="row">
    <% @flats.each do |flat| %>
      <div class="col-xs-12 col-sm-4">
          <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= flat.image_url %>');">
            <div class="card-category">Available</div>
            <div class="card-description">
              <h2><%= flat.name %></h2>
              <p><%= flat.address %></p>
            </div>
            <img class="card-user" src="https://kitt.lewagon.com/placeholder/users/tgenaitay">
          </div>
          <div>
            <i class="fas fa-users right-margin"><%= flat.number_of_guests %> </i>
            <i class="fas fa-euro-sign right-margin"><%= flat.price_per_night %></i>
          </div>
          <div class="card-links">
            <%= link_to "More info", flat_path(flat), class: 'btn btn-primary' %>
            <%= link_to "Edit", new_flat_path, class: 'btn btn-warning' %>
            <%= link_to "Remove", delete_flat(flat), class: 'btn btn-danger' %>
          </div>
      </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<%= simple_form_for(@flat) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.submit "Add my flat", class: "btn btn-primary" %>
<% end %>

app/views/flats/show.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/flats" class="navbar-wagon-brand">
    <img src="images/logo.png" alt="logo">
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <%= link_to 'Add appartment', new_flat_path, class: 'navbar-wagon-item navbar-wagon-link'%>

    <!-- Profile picture with dropdown list -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <img src="https://kitt.lewagon.com/placeholder/users/ssaunier" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="#">Profile</a></li>
          <li><a href="#">Dashboard</a></li>
          <li><a href="#">Log Out</a></li>
        </ul>
      </div>
    </div>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Host</a></li>
        <li><a href="#">Trips</a></li>
        <li><a href="#">Messagese</a></li>
      </ul>
    </div>
  </div>
</div>


<div class="container">
  <div class="row">
      <h1><%= @flat.name %></h1>
      <p><%= @flat.address %></p>
      <p><%= @flat.description %></p>
      <p><%= @flat.price_per_night %> euros</p>
      <p><%= @flat.number_of_guests %> guests</p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>